config = {
    "WestBengal": "https://cm.wb.gov.in/ncmo/Public/News.aspx",
    "Assam": "https://assam.gov.in/latest-updates-list-page",
    "Goa": "https://dip.goa.gov.in/latest-press-release",
    "Bihar": "https://governor.bih.nic.in/press-release",
    "Dehli": "https://delhi.gov.in/notice-board/notifications",
    "HimachalPradesh": "http://himachalpr.gov.in/pressrelease.aspx",
    "Chhattisgarh" :"https://cgstate.gov.in/en/all-notification?keyword=&dept=0&nType=0",
    "JammuAndKashmir":"https://home.jk.gov.in/notifications.html",
    "jharkhand": "https://jharkhand.gov.in/Home/DocumentList?doctype=eccbc87e4b5ce2fe28308fd9f2a7baf3&subdoctype=1679091c5a880faf6fb5e6087eb1b2dc",
    "Karnataka": "https://egovernance.karnataka.gov.in/19/GOVERNMENT%20ORDERS%20%20AND%20CIRCULARS/en",
    "Kerala":"https://kerala.gov.in/newsandannouncements",
    "Ladakh": "https://ladakh.gov.in",
    "MadhyaPradesh": "https://mp.gov.in/news-details",
    "Maharashtra": "https://rajbhavan-maharashtra.gov.in/en/category/press-release",
    "Manipur": "https://imphalwest.nic.in/document-category/homepage-notification",
    "Meghalaya": "https://www.meghalaya.gov.in/notifications",
    "Mizoram": "https://dipr.mizoram.gov.in/posts",
    "Nagaland" :"https://nagaland.gov.in/news",
    "Odisha": "https://home.odisha.gov.in/notifications/home-office-order",
    "Puducherry": "https://www.py.gov.in/gos-and-notification",
    "Punjab": "https://punjab.gov.in/impnotifications",
    "Rajasthan": "https://dipr.rajasthan.gov.in/press-release-list/85",
    "Sikkim": "https://www.sikkim.gov.in/media/news-announcement",
    "TamilNadu" : "https://www.tn.gov.in/press_release.php",
    "Telangana":"https://www.telangana.gov.in/news",
    "Tripura":"https://tripura.gov.in/notifications",
    "UttarPradesh":"https://information.up.gov.in/en/hi-other-information-new.aspx",
    "Uttarakhand": "https://governoruk.gov.in/category/press-release",
    "Gujarat" : "https://gad.gujarat.gov.in/personnel/notifications.htm",
    "Haryana":"https://csharyana.gov.in/en-us/LatestNew#google_vignette",
    "AndamanNicobarIslands" :"https://zpsa.andamannicobar.gov.in/Ann_all.php",
    "Chandigarh":"https://chandigarh.gov.in/news-press-releases",
    "DadraandNagarHaveliDamanDiu":"https://ddd.gov.in/document-category/latest-updates",
    "Lakshadweep":"https://lakshadweep.gov.in/notice_category/circulars/",
    "Arunachalpradesh":"https://arunachalpradesh.gov.in/advertiesment-notice.php",
    "Andhrapradesh":"https://goir.ap.gov.in",
    "IndianGovtAnnouncement": "https://www.pib.gov.in/Allrel.aspx"
}

